name: jifunzapp
description: "Une app créer pour aider les collègues étudiants dans leurs études
  en regroupant une collection des anciens questionnaires d'examens,
  interrogartions, TP, exercices, ..."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.1.0
  device_info_plus: ^10.1.0
  dropdown_button2: ^2.3.9
  easy_localization: ^3.0.7
  file_picker: ^8.0.6
  firebase_auth: ^5.1.2
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  gap: ^3.0.1
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.1
  http: ^1.2.2
  icons_plus: ^5.0.0
  image_gallery_saver: ^2.0.3
  intl: ^0.19.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  shimmer: ^3.0.0
  syncfusion_flutter_pdfviewer: ^26.2.5
  url_launcher: ^6.3.0

dev_dependencies:
  change_app_package_name: ^1.3.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/translations/
